title: Selling Fast
email: selling.fast.app@gmail.com
description: Shopify Selling Fast App
author: Selling Fast Team
url: "csa100.github.io"
baseurl: "selling-fast-site"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
